## Example use case of the tsib.CREST module

Author: Leander Kotzur

In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

### 1. Show the generator for a single profile

Import tsib.CREST

In [2]:
import tsorb.ElectricalLoadProfile as elp
import pandas as pd
import holidays

r"tsib/tsib/data/weatherdata/TRY/TRY2010_09_Jahr.dat"Initialize the object

In [15]:
path = r"C:\Users\Samuel\FH_Aachen\tsib_simuflex_fork\tsib_simuflex\tsib\data\weatherdata\TRY2015\02\TRY2015_477088122809_Somm.dat"

In [24]:
weather = pd.read_csv(path, sep=r"\s+", skiprows=32).drop([0])
weather["GHI"] = weather["B"] + weather["D"]

In [29]:
weather.index = pd.to_datetime({
    "year": 2015,
    "month": weather["MM"],
    "day": weather["DD"],
    "hour": weather["HH"] -1 ,
                })

In [30]:
weather

,RW,HW,MM,DD,HH,t,p,WR,WG,N,x,RF,B,D,A,E,IL,GHI
2015-01-01 00:00:00,4165500,2341500.0,1.0,1.0,1.0,-2.7,921.0,261.0,10.4,8.0,3.2,94.0,0.0,0.0,293.0,-336.0,0.0,0.0
2015-01-01 01:00:00,4165500,2341500.0,1.0,1.0,2.0,-3.1,921.0,276.0,9.9,8.0,3.1,94.0,0.0,0.0,293.0,-335.0,0.0,0.0
2015-01-01 02:00:00,4165500,2341500.0,1.0,1.0,3.0,-3.4,921.0,293.0,9.4,8.0,3.1,95.0,0.0,0.0,293.0,-333.0,0.0,0.0
2015-01-01 03:00:00,4165500,2341500.0,1.0,1.0,4.0,-3.4,921.0,291.0,8.4,8.0,3.1,95.0,0.0,0.0,283.0,-332.0,0.0,0.0
2015-01-01 04:00:00,4165500,2341500.0,1.0,1.0,5.0,-3.3,921.0,294.0,7.7,8.0,3.1,96.0,0.0,0.0,274.0,-332.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-12-31 19:00:00,4165500,2341500.0,12.0,31.0,20.0,-1.2,944.0,212.0,8.7,7.0,3.5,91.0,0.0,0.0,261.0,-357.0,0.0,0.0
2015-12-31 20:00:00,4165500,2341500.0,12.0,31.0,21.0,-1.5,944.0,205.0,9.8,7.0,3.5,94.0,0.0,0.0,275.0,-355.0,0.0,0.0
2015-12-31 21:00:00,4165500,2341500.0,12.0,31.0,22.0,-1.7,943.0,204.0,10.4,7.0,3.5,96.0,0.0,0.0,283.0,-351.0,0.0,0.0
2015-12-31 22:00:00,4165500,2341500.0,12.0,31.0,23.0,-2.0,943.0,213.0,10.5,8.0,3.4,96.0,0.0,0.0,276.0,-349.0,0.0,0.0
2015-12-31 23:00:00,4165500,2341500.0,12.0,31.0,24.0,-2.3,941.0,233.0,10.4,8.0,3.3,95.0,0.0,0.0,285.0,-348.0,0.0,0.0

In [48]:
de_holidays = holidays.country_holidays(country="DE",years=2015)

In [49]:
de_holidays

{datetime.date(2015, 1, 1): 'Neujahr', datetime.date(2015, 4, 3): 'Karfreitag', datetime.date(2015, 4, 6): 'Ostermontag', datetime.date(2015, 5, 1): 'Erster Mai', datetime.date(2015, 5, 14): 'Christi Himmelfahrt', datetime.date(2015, 5, 25): 'Pfingstmontag', datetime.date(2015, 10, 3): 'Tag der Deutschen Einheit', datetime.date(2015, 12, 25): 'Erster Weihnachtstag', datetime.date(2015, 12, 26): 'Zweiter Weihnachtstag'}

In [4]:
single = elp.ElectricalLoadProfile(get_hot_water = False, resample_mean=False, freq="1min")

In [5]:
load = single.run_for_year(2015)

TypeError: argument of type 'NoneType' is not iterable

In [33]:
res = single.get_rescheduled_profiles(2015)

In [34]:
res

                           Load  AppHeatGain  OccActive  OccNotActive
2015-01-01 00:00:00   60.517666    15.860196        0.0           2.0
2015-01-01 00:01:00   60.517666    15.860196        0.0           2.0
2015-01-01 00:02:00   60.517666    15.860196        0.0           2.0
2015-01-01 00:03:00   60.517666    15.860196        0.0           2.0
2015-01-01 00:04:00   60.517666    15.860196        0.0           2.0
...                         ...          ...        ...           ...
2015-12-31 23:55:00  295.343753   107.473577        0.0           2.0
2015-12-31 23:56:00  295.343753   107.473577        0.0           2.0
2015-12-31 23:57:00  295.343753   107.473577        0.0           2.0
2015-12-31 23:58:00  295.343753   107.473577        0.0           2.0
2015-12-31 23:59:00  295.343753   107.473577        0.0           2.0

[525600 rows x 4 columns]

Show hot water profile (every minute)

In [5]:
len(single.hotWater)

525600

Show profile of the occupancy activity (every 10 minutes)

In [6]:
len(single.occ_active)

52560